jparelladab/mangetoo

db/seeds.rb

Created 1 initial seed for each model. Currently Follow not working, but will fix. Please review and merge.

Initial seeds created

---

db/seeds.rb

Amended the Follow seed to amend form symbol to string and capture id from User seeds. Please review and merge.

Seed file amended

---

app/controllers/bookmarks_controller.rb
app/controllers/follows_controller.rb
app/controllers/restaurants_controller.rb
app/controllers/reviews_controller.rb
app/controllers/visits_controller.rb
app/models/restaurant.rb
app/models/user.rb
app/models/visit.rb
app/views/bookmarks/index.html.erb
app/views/follows/index.html.erb
app/views/pages/home.html.erb
app/views/restaurants/index.html.erb
app/views/restaurants/show.html.erb
app/views/reviews/index.html.erb
app/views/shared/_navbar.html.erb
app/views/visits/index.html.erb

I updated the navbar to have links to the main index pages, also worked on some of the main linking between pages with placeholder view html and placeholder links. This included some initial controller methods to have views for linking. Also included the has_many relationships in the models, as they were missing. Please review and merge. Run db:migrate.

Worked on initial linking between pages and initial controller methods

---

app/controllers/reviews_controller.rb
app/controllers/visits_controller.rb
app/models/user.rb
db/seeds.rb

Further seeds added. Minor update to model to 'has_many :reviews, through: :visits".

Updated seeds and minor tweak to user model

---

app/assets/stylesheets/components/_navbar.scss
db/seeds.rb
db/temp_seed.rb

Temp seeds file made for restaurants

seeds added to temp file

---

app/controllers/reviews_controller.rb
app/views/reviews/index.html.erb

Fixed the association of reviews to users and updated Reviews index page. Please review and merge.

Reviews index fixed

---

app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/models/bookmark.rb
app/models/restaurant.rb
app/models/review.rb
app/models/user.rb
app/models/visit.rb
db/migrate/20191125140607_create_restaurants.rb
db/migrate/20191125141837_add_attributes_to_user.rb
db/schema.rb

Default values for total rating, super_foodie and admin now added at the database level in the migrations - remember to drop, create, migrate.
Also validations added to the model level, these are commented for now (for ease of seed creation) - to be uncommented later once working on forms.
Please review and merge.

Updating validations and defaults

---

app/assets/stylesheets/config/_colors.scss

Updated the colour file and font file.

Colors updated to MangeToo

---

app/controllers/restaurants_controller.rb
app/models/restaurant.rb
app/views/restaurants/show.html.erb
config/environments/development.rb
config/environments/production.rb
db/migrate/20191126164239_create_active_storage_tables.active_storage.rb
db/schema.rb

added cloudinary config

---

db/schema.rb

Change shown in schema - to check whether should be merged or if it is an anomaly.

Schema tweaks

---

app/controllers/restaurants_controller.rb
app/models/review.rb
app/views/restaurants/show.html.erb
db/schema.rb
db/seeds.rb

Restaurant controller. Show. Find reviews from "following users" for the given restaurant. Also added validation for Reviews to make sure one visit has only one review.

restaurant controller for following users reviews

---

app/controllers/reviews_controller.rb
app/javascript/plugins/init_mapbox.js
app/views/reviews/_index_modal.html.erb
app/views/reviews/index.html.erb

Update to get the modal to work with the correct review on the reviews index.

Custom markers

---

app/views/shared/_navbar.html.erb

Added an option to search all restaurants (will need to be filtered down to connections and the user itself only in line with the general Restaurants#index option). Placeholder on the home page can be removed.
Please review and merge.

Added option for global restaurant search

---

app/controllers/bookmarks_controller.rb
app/controllers/restaurants_controller.rb
app/views/bookmarks/index.html.erb

Bookmark index page set up - cards tied to restaurant index shared partial card, so further styling will be required once shared cards are finalised. 
Please review and merge.

Bookmark index started

---

db/seeds.rb

Removed hardcoded coordinates from the seed file. Please review and merge.

Adjusted seeds file

---

app/assets/stylesheets/components/_bookmarks-restaurant-card.scss
app/assets/stylesheets/components/_card-visits-index.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_visits-index.scss
app/controllers/visits_controller.rb
app/views/bookmarks/_bookmarks-restaurant-card.html.erb
app/views/pages/home.html.erb
app/views/reviews/index.html.erb
app/views/visits/index.html.erb
db/seeds.rb

Index page for visits done, including styling and back-end. Still to be done - need to add link for seeing reviews in modal. Seeds file was also updated to get effect of previous bookings. Please review and merge.

Visits index page

---

app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

Updated the devise user create and editing pages (and user model) so that we can add images through cloudinary and create more realistic users. Please review and merge.

Updating user creation and editing pages

---

app/controllers/restaurants_controller.rb
app/views/restaurants/new.html.erb

Fixed issue with cloudinary. Please review and merge.

Cloudinary fix

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_info-window.scss
app/controllers/restaurants_controller.rb
app/views/restaurants/_info_window.html.erb
app/views/restaurants/edit.html.erb

Updating the back-end functionality for editing and updating restaurants and created the form to do so. Also tweaked styling of links on info-cards to conform styling. Please review and merge.

Updated edit and update for restaurants

---

app/javascript/packs/algolia.js
app/views/restaurants/show.html.erb
config/initializers/algoliasearch.rb

Minor tweaks to remove refs to algolia keys out of ENV.

Minor algolia updates

---

config/initializers/algoliasearch.rb

Fixed algolia

---

app/javascript/packs/algolia.js

Second fix for Algolia keys

---

db/seeds.rb

Updated the seeds to reflect addresses which work with the geocoding.

Seeds updated to give accurate geocoding

---

app/controllers/pages_controller.rb
db/seeds.rb

Updated seeds to create more data.

Updated seeds

---

app/assets/stylesheets/components/_bookmarks-restaurant-card.scss
app/assets/stylesheets/components/_card-visits-index.scss
app/assets/stylesheets/components/_card_reviews_index.scss
app/assets/stylesheets/components/_restaurant_card.scss
app/assets/stylesheets/pages/_show.scss
app/views/bookmarks/index.html.erb
app/views/restaurants/_info_window.html.erb
app/views/restaurants/show.html.erb
app/views/reviews/index.html.erb
app/views/shared/_restaurant_carousel.html.erb
app/views/visits/index.html.erb

Resized carousel throughout index pages and show page, adjusted some CSS for object-fit and overflow to make images appear better. Minor sizing tweaks related to this. Please review and merge.

Fixed formatting issues with carousel and minor CSS tweaks

---

app/views/shared/_navbar.html.erb

Navbar updated to have current user's profile.

Updated navbar for current user profile picture

---

app/views/pages/_home_modal.html.erb
app/views/pages/home.html.erb
app/views/restaurants/show.html.erb

Date formatting fixes on home page and restaurant show page. Please review and merge.

Date fixes on home page and restaurant show page

---

app/views/restaurants/show.html.erb

One more date fix for current users' reviews' dates on show page.

Fixed one more date

---

app/assets/stylesheets/pages/_bookmarks-index.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_reviews-index.scss
app/assets/stylesheets/pages/_show.scss
app/assets/stylesheets/pages/_visits-index.scss
app/views/bookmarks/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/restaurants/show.html.erb
app/views/reviews/index.html.erb
app/views/shared/_navbar.html.erb
app/views/visits/index.html.erb
db/seeds.rb

Clarifying site navigation

---

app/controllers/bookmarks_controller.rb
app/controllers/reviews_controller.rb
app/controllers/visits_controller.rb
app/views/shared/_restaurant_card.html.erb

Deleted line in controllers which was doubling the icons on the map.

Fixed icons on map

---

app/assets/stylesheets/pages/_new-review.scss
app/views/restaurants/_show_modal.html.erb
app/views/restaurants/show.html.erb
app/views/reviews/new.html.erb
app/views/visits/_visits_index_modal.html.erb

Carousel added to new review and fixed modal on show page, please review and merge.

Fixed modal on show page, added carousel for new review

---

db/seeds.rb

Updated seeds to add seeds for you all!

Update to seeds

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

Fixed navbar according to comments this morning. Please review and merge.

Fixed navbar per comments

---

app/assets/stylesheets/components/_booking-form-modal.scss
app/assets/stylesheets/components/_index.scss
app/controllers/restaurants_controller.rb
app/controllers/visits_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/init_flatpickr.js
app/javascript/plugins/init_sweetalert.js
app/views/restaurants/_booking_modal.html.erb
app/views/restaurants/show.html.erb
package.json
yarn.lock

Updated the booking function so that bookings can be made with modal + sweet alert to confirm success. Please review and merge.
Remember to bundle and yarn due to new plugins.

Book function

---

config/environments/production.rb

Updated SSL settings for setting up the domain. Please review and merge.

Updated domain settings

---

app/assets/stylesheets/components/_banner-foodies.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_bookmarks-index.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/restaurants_controller.rb
app/views/bookmarks/index.html.erb
app/views/follows/index.html.erb
app/views/pages/home.html.erb
app/views/restaurants/index.html.erb
app/views/reviews/index.html.erb

Updates to banners across the app. Some tweaks to wording and CSS. Please review and merge.

Banner updates and tweaks to wording

---

app/assets/stylesheets/components/_card-foodies.scss
app/assets/stylesheets/pages/_foodies-index.scss
app/views/follows/index.html.erb
app/views/pages/_home_modal.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

SuperFoodie seeds updated so that just celebrities are SuperFoodies. Adjusted Foodie network and added animation to all foodies cards. Please review and merge.

Updated seeds for superfoodies and adjusted foodie network page

---

app/controllers/application_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/follows/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/restaurants/show.html.erb
app/views/shared/_navbar.html.erb

Updated so that users can upload photos and their avatars will be the uploaded photos. Please review and merge.

User photos

---

public/404.html
public/500.html

Further amends to the default styling of the error pages. Please review and merge.

Further error page amends

---

db/seeds.rb

Added some more seeds. Fixed the seeds file - don't change the layout. Please review and merge.

Updated seeds, fixed seed file

---

app/assets/stylesheets/pages/_show.scss
app/controllers/bookmarks_controller.rb
app/controllers/restaurants_controller.rb
app/models/restaurant.rb
app/views/bookmarks/_bookmarks-restaurant-card.html.erb
app/views/bookmarks/_modal_restaurant_reviews.html.erb
app/views/restaurants/_reviews_modal.html.erb
app/views/restaurants/_show_modal.html.erb
app/views/restaurants/show.html.erb
app/views/shared/_restaurant_card.html.erb
app/views/visits/_previous_visit_card.html.erb

Updated visits page to singularise visits; updated logic to display (a) average rating on restaurants index modals, (b) messages if no ratings or reviews are available, (c) ratings for review; updated logic to display (a) average rating on restaurants index modals, (b) messages if no ratings or reviews are available, (c) ratings for review; updated restaurants show page to display average rating.
Please review and merge - need to migrate.

Visits page singularise visits + average rating logic and display

---

app/assets/stylesheets/components/_card-visits-index.scss
app/views/visits/_previous_visit_card.html.erb
app/views/visits/_visits_index_modal.html.erb

Fixed the margin around buttons on the visits index cards. Please review and merge.

Fixed position of buttons on visits index cards

---

app/controllers/visits_controller.rb

Changed the ordering for the purposes of the demo so the most recently created upcoming visit appears at the top. Please review and merge.

Updated to order upcoming visits by created at for the demo

---

app/assets/stylesheets/components/_card-visits-index.scss
app/controllers/bookmarks_controller.rb
app/controllers/follows_controller.rb
app/controllers/reviews_controller.rb
app/views/pages/home.html.erb
app/views/reviews/index.html.erb
app/views/visits/_modal_restaurant_reviews.html.erb
app/views/visits/_previous_visit_card.html.erb
app/views/visits/_upcoming_visit_card.html.erb
app/views/visits/_visits_index_modal.html.erb

Adjusted ordering of items on bookmarks, visits and shuffled appearance of all foodies, whilst reversing order of fellow foodies. Please review and merge.

Shuffle foodies

---

db/seeds.rb

Updated the seeds with more data for visits/reviews. Please review and merge.

Updated seeds for some more visits/reviews

---

db/seeds.rb

Fixed address and made some seeds to cover new restaurants.

seed updates

---

db/seeds.rb

Address fixes

---

app/views/pages/home.html.erb

Fixed images on home page - please review and merge.

Fixed images on home page

---

app/assets/stylesheets/components/_restaurant_card.scss
app/controllers/reviews_controller.rb
app/views/bookmarks/_bookmarks-restaurant-card.html.erb
app/views/shared/_restaurant_card.html.erb

Average rating added to restaurants and bookmarks index cards, reviews path changed to go to reviews index once a review is created. Please review and merge.

Average rating demos

---

app/assets/stylesheets/components/_card-show.scss
app/assets/stylesheets/components/_card_home.scss
app/views/pages/home.html.erb
app/views/restaurants/show.html.erb

Adjustments to mark SuperFoodie avatars on Home Page and Show Page. Please review and merge.

Superfoodie avatars

---

app/assets/stylesheets/components/_restaurant_card.scss
app/controllers/bookmarks_controller.rb
app/controllers/visits_controller.rb
app/views/bookmarks/_bookmarks-restaurant-card.html.erb
app/views/visits/_upcoming_visit_card.html.erb

Back-end done for bookmarks/visits destroy function, existing visit cancel icon now works, and icon for bookmark destroy function now included. Please review and merge.

Bookmarks and visits destroy function

---

app/controllers/visits_controller.rb

Reorder of previous visits. Please review and merge.

Reversed order of previous visits

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_visits-index.scss
app/controllers/restaurants_controller.rb
app/views/bookmarks/index.html.erb
app/views/reviews/index.html.erb
app/views/visits/index.html.erb

Adds some messages when user has no visits, bookmarks or review.
Probably not worth merging until after demo day.

Fixing bug no reviews displayed grey box
